import React, { useRef } from "react";
import { getPlaneId } from "@coconut-xr/natuerlich";
import { TrackedPlane, useTrackedPlanes } from "@coconut-xr/natuerlich/react";
import { interactionGroups, RigidBody } from "@react-three/rapier";
import type { RapierRigidBody } from "@react-three/rapier";

interface BuildPhysicalPlanesProps {
  children?: React.ReactNode;
  debug?: boolean;
}

/**
 * Transforms of Tracked Planes into Rigid Bodies.
 *
 * @param {children} props.children - The children of the mesh.
 * @param {excludeGlobalMesh} props.excludeGlobalMesh - Whether to exclude the global mesh.
 * @param {debug} props.debug - Whether to enable debug mode, which will add wireframe to the meshes.
 *
 * @note The planes are generated by the space setup data from a Meta Quest or other compatible headset,
 * which saves a layout of your room + allows you to map your furiniture.
 /**
 * @returns A group of rigid bodies with all tracked planes being a THREE.Mesh.
 */
export function BuildPhysicalPlanes({
  children,
  debug = false,
}: BuildPhysicalPlanesProps) {
  const planes = useTrackedPlanes();
  const planeRef = useRef<THREE.Mesh>(null);
  const rigidBodyRef = useRef<RapierRigidBody>(null);

  return (
    <group name="room-planes">
      {planes?.map((plane) => (
        <RigidBody
          key={getPlaneId(plane)}
          // using same rigidBodyRef for all meshes
          // NEED TO CHANGE
          ref={rigidBodyRef}
          colliders="cuboid"
          type="fixed"
          collisionGroups={interactionGroups([6], [0, 1, 2, 3, 4, 5, 8])}
        >
          <TrackedPlane
            plane={plane}
            ref={planeRef}
            // meshRef={meshRef}
            // rigidBodyRef={rigidBodyRef}
          >
            {children ? (
              children
            ) : (
              <meshPhongMaterial
                wireframe={debug}
                opacity={debug ? 100 : 0}
                transparent={!debug}
                color={debug ? "red" : "white"}
              />
            )}
          </TrackedPlane>
        </RigidBody>
      ))}
    </group>
  );
}
