import React, { useRef } from "react";
import { getMeshId } from "@coconut-xr/natuerlich";
import { TrackedMesh } from "@coconut-xr/natuerlich/react";
import type { ExtendedXRMesh } from "@coconut-xr/natuerlich/react";
import { interactionGroups, RigidBody } from "@react-three/rapier";
import type { RapierRigidBody } from "@react-three/rapier";

interface BuildPhysicalMeshesProps {
  meshes: readonly ExtendedXRMesh[] | undefined;
  children?: React.ReactNode;
  excludeGlobalMesh?: boolean;
  debug?: boolean;
}

/**
 * Transforms Tracked Meshes into Rigid Bodies.
 *
 * @param {meshes} props.meshes - The meshes to be transformed into rigid bodies. Retrievable with `useTrackedMeshes` from `@coconut-xr/natuerlich`.
 * @param {children} props.children - The children of the mesh.
 * @param {excludeGlobalMesh} props.excludeGlobalMesh - Whether to exclude the global mesh.
 * @param {debug} props.debug - Whether to enable debug mode, which will add wireframe to the meshes.
 *
 * @note The meshes are generated by the space setup data from a Meta Quest or other compatible headset,
 * which saves a layout of your room + allows you to map your furiniture.
 *
 * @returns A group of rigid bodies with all tracked meshes being a THREE.Mesh.
 */
export function BuildPhysicalMeshes({
  children,
  excludeGlobalMesh = false,
  debug = false,
  meshes,
}: BuildPhysicalMeshesProps) {
  const meshRef = useRef<THREE.Mesh>(null);
  const rigidBodyRef = useRef<RapierRigidBody>(null);

  return (
    <group name="room-meshes">
      {meshes?.map((mesh) => {
        if (excludeGlobalMesh && mesh.semanticLabel === "global mesh")
          return null;

        return (
          <RigidBody
            name={mesh.semanticLabel}
            key={getMeshId(mesh)}
            type="fixed"
            colliders={
              mesh.semanticLabel === "global mesh" ? "trimesh" : "hull"
            }
            ref={rigidBodyRef}
            collisionGroups={interactionGroups([7], [0, 1, 2, 3, 4, 5, 8])}
          >
            <TrackedMesh mesh={mesh} ref={meshRef}>
              {children ? (
                children
              ) : (
                <meshBasicMaterial
                  wireframe={debug}
                  transparent={!debug}
                  opacity={debug ? 100 : 0}
                  color={debug ? "purple" : "white"}
                />
              )}
            </TrackedMesh>
          </RigidBody>
        );
      })}
    </group>
  );
}
